#Esse programa usa umas funções para ver informações de uma variável.
n = input("Digite alguma coisa: ")
print("O tipo primitivo desse valor é {}".format(type(n)))
print("Só tem espaços? {}".format(n.isspace()))
print("É um número? {}".format(n.isnumeric()))
print("É alfabético? {}".format(n.isalpha()))
print("É alfanumérico? {}".format(n.isalnum()))
print("Está em maiúsculo? {}".format(n.isupper()))
print("Está em minúsculo? {}".format(n.islower()))
print("Está capitalizada? {}".format(n.istitle()))
